config/routes.rb
Rails.application.routes.draw do

  root to: "monthly_budgets#new"
  devise_for :users
  # , controllers: { registrations: 'registrations' }

  # post   '/categories', to: 'monthly_budget#create'
  get '/monthly_budgets/listing', to: 'monthly_budgets#listing'
  resources :monthly_budgets
  resources :categories do
    resources :expenses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :monthly_budget
  has_many :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category
end

app/models/monthly_budget.rb
class MonthlyBudget < ApplicationRecord
  belongs_to :user
  has_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  has_many :monthly_budgets
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  @@monthly_budget = ' '
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @month = @@monthly_budget.month
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @@category = @category
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :target)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expenses
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET categories/1/expenses
  def index
    @expenses = @category.expenses
  end

  # GET categories/1/expenses/1
  def show
  end

  # GET categories/1/expenses/new
  def new
    @expense = @category.expenses.build
  end

  # GET categories/1/expenses/1/edit
  def edit
  end

  # POST categories/1/expenses
  def create
    @expense = @category.expenses.build(expense_params)

    if @expense.save
      redirect_to([@expense.category, @expense], notice: 'Expense was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT categories/1/expenses/1
  def update
    if @expense.update_attributes(expense_params)
      redirect_to([@expense.category, @expense], notice: 'Expense was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE categories/1/expenses/1
  def destroy
    @expense.destroy

    redirect_to category_expenses_url(@category)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expenses
      @category = Category.find(params[:category_id])
    end

    def set_expense
      @expense = @category.expenses.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def expense_params
      params.require(:expense).permit(:name, :amount_spent)
    end
end

app/controllers/monthly_budgets_controller.rb
class MonthlyBudgetsController < ApplicationController
  before_action :authenticate_user!
  

  def index
    redirect_to new_monthly_budget_path
  end

  def new
    @monthly_budget = MonthlyBudget.new
  end

  def create
    @monthly_budget = MonthlyBudget.new monthly_budget_params
    @monthly_budget.user = current_user
    if @monthly_budget.save
      @@monthly_budget = @monthly_budget
      flash[:success] = "#{@monthly_budget.month} was successfully created."
      redirect_to categories_path(params[:id])
    else
      flash[:danger] = "Must enter current month"
     
      render :new
    end
  end

  def listing
    @monthly_budgets = current_user.monthly_budgets.all
  end

  private

  def monthly_budget_params
    params.require(:monthly_budget).permit(:month, :user_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 private

 def sign_up_params
   params.require(:user).permit(:email, :password, :password_confirmation)
 end

 def account_update_params
   params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/monthly_budget_helper.rb
module MonthlyBudgetHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :target %>
    <%= f.number_field :target %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories for the month of <%=@month-%></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Target</th>
      <th>Amount Spent</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.target %></td>
        <td><%= category.expenses.pluck('amount_spent').sum %></td>

        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Target:</strong>
  <%= @category.target %><br><br>
  <strong>Spent so far:</strong>
  <%= @category.expenses.pluck('amount_spent').sum %><br><br>
  <strong>Budget left:</strong>
  <%= @category.target - @category.expenses.pluck('amount_spent').sum %>
</p>

<%= link_to 'View expenses', category_expenses_path(@category) %> |
<%= link_to 'Add expense', new_category_expense_path(@category) %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/expenses/_form.html.erb
<%= form_for([@expense.category, @expense]) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :amount_spent %><br />
    <%= f.number_field :amount_spent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', [@expense.category, @expense] %> |
<%= link_to 'Back', category_expenses_path(@expense.category) %>

app/views/expenses/index.html.erb
<h1>Listing expenses for <%=@category.name%></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Amount spent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.name %></td>
    <td><%= expense.amount_spent %></td>
    <td><%= link_to 'Show', [expense.category, expense] %></td>
    <td><%= link_to 'Edit', edit_category_expense_path(expense.category, expense) %></td>
    <td><%= link_to 'Destroy', [expense.category, expense], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expense', new_category_expense_path(params[:category_id]) %>
<%= link_to 'Back', category_path(params[:category_id]) %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', category_expenses_path(@expense.category) %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @expense.name %>
</p>

<p>
  <b>Amount spent:</b>
  <%= @expense.amount_spent %>
</p>


<%= link_to 'Edit', edit_category_expense_path(@expense.category, @expense) %> |
<%= link_to 'Back', category_expenses_path(@expense.category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <nav>
   <% if current_user %>
     <p>Hello, <%= current_user.email %>!
     <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
     <%= link_to 'Budgets', monthly_budgets_path %>
    

   <% else %>
     <%= link_to 'Register', new_user_registration_path %>
     <%= link_to 'Login', new_user_session_path %>
   <% end %>
  </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/monthly_budgets/index.html.erb
<h1>Monthly Budget</h1>
<%= form_for :monthly_budget do |f| %>
  Month: <%= f.text_field :month %>
  <%= f.submit "Create Budget" %>
<% end %>

app/views/monthly_budgets/listing.html.erb
<tbody>
  <%@monthly_budgets.each do |monthly_budget|%>
     <td><%= link_to "#{monthly_budget.month}", categories_path%></td><br>
  <%end%>
</tbody>

app/views/monthly_budgets/new.html.erb
<h1>Monthly Budget</h1>
<%= form_for @monthly_budget do |f| %>
  Month: <%= f.text_field :month %>
  <%= f.submit "Create Budget" %>
<% end %>